source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EGTracker_Example', :exclusive => true do
  pod 'EGTracker', :path => '../'
end

target 'EGTracker_Tests', :exclusive => true do
  pod 'EGTracker', :path => '../'

  
end
